export const FETCH_INSPECTORS = 'FETCH_INSPECTORS';
export const SET_DEFAULT_INSPECTORS = 'SET_DEFAULT_INSPECTORS';
export const FETCH_CALENDAR = 'FETCH_CALENDAR';
export const SET_DEFAULT_CALENDAR = 'SET_DEFAULT_CALENDAR';
export const FETCH_INSPECTIONS = 'FETCH_INSPECTIONS';
export const SET_DEFAULT_INSPECTIONS = 'SET_DEFAULT_INSPECTIONS';